blank_lines_upper_bound = 2
fn_call_width = 130
fn_single_line = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 160
merge_derives = false
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
